name: 'MovieShare'
version: 0.0.1
description: An absolute bare-bones web app.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
  http: "^0.11.3+3"
  mdl: "^1.17.3"
  di: "^3.3.0"

transformers:
- di
- dart_to_js_script_rewriter
